### PR TITLE
Notify support

### PR DESCRIPTION
**Pull request by colthreepv**
Added support to notifyProgram 😉 appeared in 1.2

Issue ref: #15

### CODE REVIEW

**Comment by blacklabelops** [comment]
Your pull request does not compile: [WARNING]: Empty continuation line found in:
    RUN export JOBBER_HOME=/tmp/jobber &&

**Comment by colthreepv** [comment]
I have seen this warning, but it was already present on master checkout (135df2523feb)

I tried to google it, but my results were inconclusive. although it does not prevent image creation

**EDIT**: mistery solved, [comments get treated as "empty continuation lines"](https://github.com/moby/moby/pull/34333), removing all the comments in Dockerfile will make the warning go away (but it isn't the scope of this PR)

**Comment by blacklabelops** [comment]
My fault, warning does not break build. Didn't see the message 'successfull' at the end.

**Comment by blacklabelops** [comment]
Thank you for the feature!

**Pull request merged**
