### PR TITLE
Install docker

### PR DESCRIPTION
**Pull request by mcanevet**
Allows to run:

```
$ docker run -d \
    --volume /var/run/docker.sock:/var/run/docker.sock
    --name jobber \
    -e "JOB_NAME1=TestDocker" \
    -e "JOB_COMMAND1=docker run tutum/hello" \
    blacklabelops/jobber
```

### CODE REVIEW

**Comment by blacklabelops** [comment]
jobber-cloud/Dockerfile aka blacklabelops/cron-cloud already contains Docker and works exactly as you intended. Please build like this:

Readme can be found [HERE](https://github.com/blacklabelops/jobber-cron/tree/master/jobber-cloud)

```
$ docker build -t blacklabelops/jobber .
$ cd jobber-cloud/
$ docker build -t blacklabelops/cron-cloud .
```

or just pull blacklabelops/cron-cloud from dockerhub.

**Comment by blacklabelops** [comment]
Note: This image is deprecated and will move to a branch named `centos` shortly. The refactored minimal image containing Jobber and Docker/AWS/Gcloud etc. on Alpine can be found on branch `alpine`.

**Comment by mcanevet** [comment]
@blacklabelops I just found your cron-cloud image in the mean time. Thanks

**Comment by blacklabelops** [comment]
Glad you like it! The new minimized image with less than 100MB will come soon!

**Pull request closed without merging**
